### ISSUE TITLE
Feature request: Link to specific view

### ISSUE THREAD

**Issue by BartVB** [NLeSC/ahn-pointcloud-viewer#18]
The easiest way to explain is an example:
https://www.google.com/maps/@51.9816396,5.9123597,15z

Google maps allows users to copy/paste the URL to save or share their view of the map. It would be great if the pointclouds viewer had a similar feature. This would make communication about particular sections of the map/pointcloud much easier.

**Comment by Maartenvm** [comment]
I realise it's a bit late, but there's good news on this. The feature has been implemented in the new develop branch, we will update the production version of the viewer soon(tm).
