### ISSUE TITLE
ahn-pointcloud-viewer

### ISSUE THREAD

**Issue by kowibo** [NLeSC/ahn-pointcloud-viewer#20]
Up tot January this year we were able to download Point Cloud files (.laz) from the ahn-pointcloud-viewer.
But now we receive an error when we use this service.
"Count Points" doesn't work (remains "0") en pushing the submit-button returns the next error:
"_for some reason Submit failed_".

Is this service down?

**Comment by thomascs** [comment]
I have the same problem. Count points remains 0 and I always get the "for some reason Submit failed" error when trying to download the points.

**Comment by kowibo** [comment]
Today we were lucky to find the ahn-pointcloud-viewer working again!
