### ISSUE TITLE
No points visible in Firefox (55.0.2, 64-bit)

### ISSUE THREAD

**Issue by arnikz** [NLeSC/ahn-pointcloud-viewer#29]
`TypeError: jsfunc.toString(...).match(...) is null  6936ccc1-315b-48ef-a705-de694720b55c:1:13258`

**Comment by sverhoeven** [comment]
Let's print a warning that Firefox is not supported, you should use Chrome or Edge

**Comment by sverhoeven** [comment]
The laz parser for potree 1.5 works, but the one of 1.3 does not.
